### ISSUE TITLE
Undlad brug af Join-NAVApplicationObjectFile

### ISSUE THREAD

**Issue by NiHanDK** [joandrsn/finsql-tools#1]
Der er en problemstilling når man anvender Join-NAVApplicationObjectFile, som gør at når denne anvendes undlader den rapporter med PDFFontEmbedding, samt pages med enkelte opsætninger.

Gør istedet anvendelse af samme funktionalitet som i Build-scriptet

**Comment by joandrsn** [comment]
Jeg ser umiddelbart 3 løsninger:

1. Udfør kommandoen for at joine filer i terminalen til fulde
2. Inkluder et powershell modul sammen med extensionen
3. Kræv at et powershell modul er installeret i forvejen

Løsning 1 vil medføre at terminalen får følgende linjer skrevet ind når den gamle `Join-NAVApplicationObjectFile` udføres:

```
$StreamWriter = New-Object -TypeName "System.IO.FileStream" -ArgumentList $tempImportFile, 'Create', 'ReadWrite'

foreach ($importfile in $files) {
  $PathObj = Resolve-Path $importfile
  $StreamReader = New-Object -TypeName "System.IO.FileStream" -ArgumentList $PathObj.Path, 'Open', 'Read'
  $StreamReader.CopyTo($StreamWriter)
  
  $StreamReader.Close()
  $StreamReader.Dispose()
}
$StreamWriter.Close()
$StreamWriter.Dispose()
```

Løsning 2 vil kræve at der bliver pakket en extension med.
I starten af eksekvering af scripts vil der så stå:
`Import-Module '"C:\Users\temp\.vscode\extensions\finsql-tools-0.4.0\psscripts\workarounds.psm1"'

Løsning 3 vil kræve at der bliver udført et check om modulet er installeret inden der bliver udført første kommando. Så kunne der vises en rød fejl hvis det ikke er der. Denne løsning kunne måske udvides med at den kun vil bruge det eksterne modul hvis det er installeret.

Har du en preference?

**Comment by NiHanDK** [comment]
Løsning 1 var den jeg lige havde tænkt som fin nok. De læser ikke andet end de nederste "Fejl" linjer alligevel
